export const SEND_EMAIL_SUCCESS = "SEND_EMAIL_SUCCESS";
export const SEND_EMAIL_FAIL = "SEND_EMAIL_FAIL";

export const SET_CODE_IS_EXPIRE = "SET_CODE_IS_EXPIRE";
export const EMAIL_VERIFICATION_SUCCESS = "EMAIL_VERIFICATIO_SUCCESS";
export const EMAIL_VERIFICATION_FAIL = "EMAIL_VERIFICATIO_FAIL";

export const REGISTER_SUCCESS = "REGISTER_SUCCESS";
export const REGISTER_FAIL = "REGISTER_FAIL";

export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAIL = "LOGIN_FAIL";
export const LOGOUT = "LOGOUT";

export const SET_MESSAGE = "SET_MESSAGE";
export const CLEAR_MESSAGE = "CLEAR_MESSAGE";
